name: Testing

on:
  workflow_call:

jobs:
  e2e:
    runs-on: ubuntu-latest

    steps:
      - name: Extract ref
        id: extract-ref
        run: echo "ref=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ steps.extract-ref.outputs.ref }}

      - name: Build image and run tests
        shell: bash
        run: |
          set -e
          docker build . -t s3-nfs
          ./tests/e2e/index.sh
