name: Renovate dependencies

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  renovate:
    runs-on: ubuntu-latest

    steps:
      - name: Extract ref
        id: extract-ref
        run: echo "ref=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ steps.extract-ref.outputs.ref }}

      - name: Generate Renovate app token
        id: renovate-app-token
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ secrets.RENOVATE_APP_ID }}
          private_key: ${{ secrets.RENOVATE_APP_PEM }}
          repositories: ${{ toJSON(github.repository) }}

      - name: Renovate dependencies
        uses: renovatebot/github-action@v40.2.5
        with:
          token: ${{ steps.renovate-app-token.outputs.token }}
        env:
          RENOVATE_AUTODISCOVER: true
          RENOVATE_AUTODISCOVER_FILTER: ${{ github.repository }}
          RENOVATE_AUTOMERGE: true
          RENOVATE_PR_HOURLY_LIMIT: 0
