name: Update package

on:
  push:
    tags: ['*']

jobs:
  update-package:
    name: Update package
    runs-on: ubuntu-latest
    steps:
      - id: update-package
        name: Update package
        uses: nedix/actions/update-package@v0.8.11
        with:
          platforms: linux/amd64,linux/arm64/v8
          registry: docker.io
          registry_path: nedix/s3-nfs
          registry_username: ${{ secrets.DOCKERHUB_USERNAME }}
          registry_password: ${{ secrets.DOCKERHUB_PAT }}
